apiVersion: v2
name: cpn-job
description: Creates Job in Kubernetes cluster.
type: application
version: 1.1.0
appVersion: 1.0.0
maintainers:
  - name: cloud-pi-native
    email: cloudpinative-relations@interieur.gouv.fr
    url: https://cloud-pi-native.fr
