{{- if .Values.opencds.enabled }}
{{- if .Values.opencds.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cpnConsole.fullname" . }}-opencds
  labels:
    {{- include "cpnConsole.opencds.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cpnConsole.fullname" . }}-opencds
  minReplicas: {{ .Values.opencds.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.opencds.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.opencds.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.opencds.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.opencds.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.opencds.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
