{{- if .Values.opencds.enabled }}
{{- if or .Values.global.secrets .Values.opencds.secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cpnConsole.fullname" . }}-opencds
  labels: {{- include "cpnConsole.opencds.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "cpnConsole.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.opencds.secrets -}}
  {{- include "cpnConsole.secret" .Values.opencds | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
