apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.application.destination.namespace }}
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- .Values.common | toYaml | nindent 4 }}
