{{- if or .Values.global.secrets .Values.opencds.secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cpnOpenCDSMockoon.fullname" . }}-opencds
  labels: {{- include "cpnOpenCDSMockoon.opencds.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "cpnOpenCDSMockoon.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.opencds.secrets -}}
  {{- include "cpnOpenCDSMockoon.secret" .Values.opencds | indent 2 }}
  {{- end -}}
{{- end -}}
