{{- if .Values.strangler.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cpnConsole.fullname" . }}-strangler
  labels:
    {{- include "cpnConsole.strangler.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cpnConsole.fullname" . }}-strangler
  minReplicas: {{ .Values.strangler.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.strangler.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.strangler.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.strangler.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.strangler.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.strangler.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
