{{- if or .Values.global.secrets .Values.strangler.secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cpnConsole.fullname" . }}-strangler
  labels: {{- include "cpnConsole.strangler.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "cpnConsole.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.strangler.secrets -}}
  {{- include "cpnConsole.secret" .Values.strangler | indent 2 }}
  {{- end -}}
{{- end -}}
