apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpnConsole.fullname" . }}-backend
  labels:
    {{- include "cpnConsole.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.container.port }}
      protocol: TCP
  selector:
    {{- include "cpnConsole.backend.selectorLabels" . | nindent 4 }}
