# -- Provide a name in place of the default application name.
nameOverride: ""
# -- String to fully override the default application name.
fullnameOverride: ""

global:
  # -- For security context depending of the cluster distribution.
  platform: kubernetes

# Job configuration.
job:
  # -- Playbook name.
  name: "example-playbook"
  # -- (string) Name of the DsoSocleConfig to use as source-of-truth.
  dscName: null
  # -- Git branch or tag to checkout before applying the Ansible playbook.
  targetRevision: "main"
  serviceAccount:
    # -- Create a service account for the job.
    create: true
    # -- Annotations applied to created service account.
    annotations: {}
    # -- Service account name.
    name: ""
  # -- Job restart policy (e.g., Never or OnFailure).
  restartPolicy: OnFailure
  # -- Optional maximum time in seconds before de Pod is killed (no matter of the backoffLimit).
  activeDeadlineSeconds: null
  # -- Number of retries before setting de Job status to failed.
  backoffLimit: 6
  image:
    # -- Repository to use for the job.
    repository: ghcr.io/cloud-pi-native/git-ansible
    # -- Tag to use for the job.
    ## Overrides the image tag whose default is the chart appVersion.
    tag: ""
    # -- Pull policy for the job image.
    pullPolicy: IfNotPresent
  # -- Kubernetes annotations to apply to the job resource.
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  # -- (Optional) Extra environment variables to pass to the job container.
  extraEnv: []
  #   - name: MY_CUSTOM_VAR
  #     value: "custom-value"
  # -- (Optional) Extra volumes to mount into the job container.
  extraVolumes: []
  #   - name: my-random-volume
  #     configMap:
  #       name: my-random-config
  # -- (Optional) Extra volume mounts for the job container.
  extraVolumeMounts: []
  #   - name: my-random-volume
  #     mountPath: /random/path
  #     readOnly: true

cronJob:
  # -- Create a cronJob.
  create: false
  # -- Playbook name if different from job.
  name: ""
  # -- CronJob schedule.
  schedule: "0 */6 * * *"
