# -- Informations communes, notamment appliquées en label sur les différents objets
common:
  dso/project: project
  dso/project.slug: project
  dso/environment: env
application:
  destination:
    # -- Nom du namespace applicatif cible
    namespace: app1
  quota:
    # -- (int) Quota CPU pour le namespace
    cpu:
    # -- (int) Quota GPU pour le namespace
    gpu:
    # -- Quota mémoire pour le namespace
    memory:
  vault:
    # -- URL du Vault à utiliser par Vault Secret Operator
    url:
    # -- Nom du Key Value store dans Vault
    kvName: forge-dso
    # -- ID du rôle à utiliser (méthode AppRole)
    roleId:
    # -- Secret de connexion avec ce rôle
    secretId:
    # -- Répertoire racine des projets à utiliser dans Vault
    projectsRootDir: forge-mi/projects
  sleep:
    enabled: true
    # -- Préfixes d'environnement pour lesquels le sleep n'est pas créé (ex. prod, prd)
    skipEnvironmentPrefixes:
      - prod
      - prd
    sleepAt: "18:30"
    timeZone: Europe/Rome
    wakeUpAt: "7:30"
    weekdays: 1-5
    suspendCronJobs: true
