{
 "title": "PolicyReport Details",
 "tags": [
  "Security",
  "Kyverno",
  "Reports"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ocp_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(policy_report_result,ocp_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(policy_report_result{ocp_cluster=~\"$ocp_cluster\"},exported_namespace)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "label_values(policy_report_result, policy)"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "label_values(policy_report_result, category)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(policy_report_result, severity)"
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": "label_values(policy_report_result, kind)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(policy_report_result, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{status=\"pass\", ocp_cluster=~\"$ocp_cluster\", severity=~\"medium|high|low\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Fail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{status=\"fail\", ocp_cluster=~\"$ocp_cluster\", severity=~\"medium|high|low\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Fail ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{status=\"fail\", ocp_cluster=~\"$ocp_cluster\", severity=~\"medium|high|low\"}) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Pass Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"pass\", ocp_cluster=~\"$ocp_cluster\" } > 0) by (exported_namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Policy Fail Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"fail\", ocp_cluster=~\"$ocp_cluster\" } > 0) by (exported_namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Policy Warning Status",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"warn\", ocp_cluster=~\"$ocp_cluster\" } > 0) by (exported_namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Policy Error Status",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"error\", ocp_cluster=~\"$ocp_cluster\" } > 0) by (exported_namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", ocp_cluster=~\"$ocp_cluster\" } > 0) by (status, exported_namespace)",
     "legendFormat": "{{namespace}} {{ status }}"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(delta(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", exported_namespace=~\"$namespace\", status=\"fail\", ocp_cluster=~\"$ocp_cluster\" }[$__range])) by (exported_namespace,category,policy,rule,kind,name,severity,status,source)"
    }
   ]
  }
 ]
}