{
 "title": "Security Overview",
 "description": "overview de securité",
 "tags": [
  "Security",
  "Falco",
  "Kyverno",
  "Trivy"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "ocp_cluster", "label": "Cluster", "query": { "query": "label_values(ocp_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "FALCO",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(falco_events{ocp_cluster=~\"$ocp_cluster\", priority=~\"Critical|Warning|Notice\"}[$__range])) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRIVY",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(trivy_image_vulnerabilities{severity=~\"Critical|High|Medium\", ocp_cluster=~\"$ocp_cluster\"}) by (image_repository,image_tag, severity) ) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KYVERNO Validate/Mutate FAIL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(policy_report_result{severity=~\"high|medium\", status=\"fail\", ocp_cluster=~\"$ocp_cluster\" }[$__range])) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dashboard Detais", "type": "dashlist", "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 } },
  {
   "title": "Présentation des Outils de Securités",
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "options": {
    "content": "**Falco:**\nOutil de détection des comportements anormaux et suspects dans les applications conteneurisées. Il s'intègre au noyau Linux via eBPF pour fournir des capacités de surveillance et de sécurité en temps réel.\n\n**Kyverno:**\nFramework pour Kubernetes qui permet de valider, muter et générer des configurations en utilisant des politiques déclaratives.\n\n**Trivy:**\nL'opérateur Trivy tire parti de Trivy pour analyser en continu votre cluster Kubernetes à la recherche de vulnérabilités dans les images de conteneurs."
   }
  }
 ]
}