{
 "title": "Trivy Operator - Vulnerabilities",
 "description": "This is a modern dashboard for the Trivy Operator from Aqua Security. Made to take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Security",
  "Trivy"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ocp_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(trivy_image_vulnerabilities,ocp_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Target Namespace",
    "query": {
     "query": "label_values(trivy_image_vulnerabilities{ocp_cluster=~\"$ocp_cluster\"},namespace)"
    }
   },
   { "name": "severity", "label": "severity", "query": { "query": "label_values(severity)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vulnerability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\nsum(\n  sum(\n    trivy_image_vulnerabilities{severity=~\"Critical|High|Medium|low\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"})\n   by (image_repository,image_tag, severity) > 0 ) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL Image with Vulnerability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group(\n  sum(\n    trivy_image_vulnerabilities{severity=~\"$severity\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"})\n   by (image_repository,image_tag) > 0 ) by (image_repository,image_tag))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total vulnerabilities by namespaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{ocp_cluster=~\"$ocp_cluster\",namespace=~\"$namespace\", severity=~\"$severity\"}) by (exported_namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total vulnerabilities by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vulnerability Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Vulnerability Count per Image and Severity",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max(trivy_image_vulnerabilities{namespace=~\"$namespace\", ocp_cluster=~\"$ocp_cluster\", severity=~\"$severity\"}) by (exported_namespace, image_registry, image_repository, image_tag, severity) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Critical\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (exported_namespace,image_repository,image_tag)"
    },
    {
     "expr": "min(trivy_image_vulnerabilities{severity=\"High\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (exported_namespace,image_repository,image_tag)"
    },
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Medium\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (exported_namespace,image_repository,image_tag)"
    },
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Low\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (exported_namespace,image_repository,image_tag)"
    },
    {
     "expr": "max(trivy_image_vulnerabilities{severity=\"Unknown\", ocp_cluster=~\"$ocp_cluster\", namespace=~\"$namespace\"}) by (exported_namespace,image_repository,image_tag)"
    }
   ]
  },
  {
   "title": "Detaillled CVE vulnerabilities",
   "type": "table",
   "description": "Require operator.metricsVulnIdEnabled: true",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id{vuln_id=~\"CVE.*\", namespace=~\"$namespace\", ocp_cluster=~\"$ocp_cluster\", severity=~\"$severity\"}) by (exported_namespace, image_registry, image_repository, image_tag, vuln_id, severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CVE Vulnerability Count",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id{vuln_id=~\"CVE.*\", namespace=~\"$namespace\", ocp_cluster=~\"$ocp_cluster\", severity=~\"$severity\"}) by (vuln_id, severity)"
    }
   ]
  }
 ]
}