{{- range  $cluster := .Values.clusters }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $cluster }}-cluster-secret
  namespace: argo-cpin
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: {{ $.Values.vault.kvName }}
  path: clusters/cluster-{{ $cluster }}/argocd-cluster-secret
  destination:
    create: true
    name: {{ $cluster }}-cluster-secret
    labels:
      'argocd.argoproj.io/secret-type': 'cluster'
{{- end }}
