---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dso-project # Pour les Applications déployées par la Console DSO
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Evite la suppression avant les Applications
spec:
  description: Project to deploy DSO Applications
  destinations:
    - name: "*"
      namespace: "*"
      server: "*"
  sourceRepos:
    - "https://github.com/cloud-pi-native/helm-charts.git"
    - "{{ .Values.dsoZoneRepo }}"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dso-appset
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Evite la suppression avant l'instance ArgoCD
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: {{ .Values.dsoZoneRepo }}
        revision: HEAD
        files:
          - path: "**/values.yaml" # project/cluster/environment/values.yaml
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
        - /spec/sources/0/targetRevision
  template:
    metadata:
      name: {{"\"{{ index .path.segments 0 }}-{{ index .path.segments 1 }}-{{ index .path.segments 2 }}-root\"" }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: dso-console
        dso/projet: {{"\"{{ index .path.segments 0 }}\""}}
        dso/environment: {{"\"{{ index .path.segments 2 }}\""}}
    spec:
      project: dso-project
      sources:
        - repoURL: https://github.com/cloud-pi-native/helm-charts.git
          targetRevision: {{"\"{{ .argocd.envChartVersion }}\""}}
          path: charts/dso-env
          helm:
            valueFiles:
              - {{"\"$values/{{ .path.path }}/{{ .path.filename }}\""}}
            values: |
              argocd:
                namespace: {{ .Release.Namespace }}
        - repoURL: "{{ .Values.dsoZoneRepo }}"
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .Release.Namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
