apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: argocd-vault-connection
  namespace: {{ .Release.Namespace }}
spec:
  address: {{ .Values.vault.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vso-approle
  namespace: {{ .Release.Namespace }}
stringData:
  id: {{ .Values.vault.secretId }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  vaultConnectionRef: argocd-vault-connection
  method: appRole
  mount: approle
  appRole:
    roleId: {{ .Values.vault.roleId }}
    secretRef: vso-approle
  allowedNamespaces: 
    - {{ .Release.Namespace }}
