{{- if .Values.cronJob.create -}}
{{- $playbookName := .Values.cronJob.name | default .Values.job.name }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cpnAnsibleJob.fullname" . }}
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
{{ include "cpnAnsibleJob.jobPodSpec" (dict "playbookName" $playbookName "Values" .Values "Chart" .Chart "Release" .Release) | indent 4 }}
{{- end }}
