{{- $playbookName := .Values.job.name }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cpnAnsibleJob.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.job.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{ include "cpnAnsibleJob.jobPodSpec" (dict "playbookName" $playbookName "Values" .Values "Chart" .Chart "Release" .Release) }}
