{{- if and .Values.backup.enabled .Values.backup.s3Credentials.create }}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.backup.s3Credentials.secretName | default (printf "%s-%s" (include "cpnCnpg.fullname" .) "pg-cluster") }}
  labels:
    {{- include "cpnCnpg.labels" . | nindent 4 }}
data:
  {{ .Values.backup.s3Credentials.accessKeyId.key | indent 4 }}: {{ .Values.backup.s3Credentials.accessKeyId.value | b64enc }}
  {{ .Values.backup.s3Credentials.secretAccessKey.key | indent 4 }}: {{ .Values.backup.s3Credentials.secretAccessKey.value | b64enc }}
{{- end }}
